### ISSUE TITLE
Any plan to publish to maven central or jcenter?

### ISSUE THREAD

**Issue by wuhx** [aliyun-beta/aliyun-jclouds#3]
Trying to use this in my project,  but can't find an easy way.
Thanks!

**Comment by anyways** [comment]
你好，SLB代码中还有部分功能不稳定，目前正在调试中，待全部功能测试通过将发布到maven仓库中，请耐心等待，请见谅。

**Comment by anyways** [comment]
Aliyun-jclouds is synchronized to maven central,please read README.md for more details.
